### ISSUE TITLE
Consider renaming PARSE-STRING

### ISSUE THREAD

**Issue by thomp** [Ramarren/cl-parser-combinators#2]
Is it likely that others may find the ability of PARSE-STRING to handle sequences apart from strings useful? 

```
 PARSER-COMBINATORS> (tree-of (current-result (parse-string (find? "bb") '(#\a #\a #\b #\b #\c #\c))))
 "bb"
 PARSER-COMBINATORS> (tree-of (current-result (parse-string (find? "bb") '#(#\a #\a #\b #\b #\c #\c))))
 "bb"
```

Would it be more accurate (and perhaps better advertise the potential of CL-PARSE-COMBINATORS?) to rename PARSE-STRING as PARSE-SEQUENCE or something along those lines?

**Comment by Ramarren** [comment]
Changed in df86968dc42158e5cc2b205200867185dd8b5cb9 . Added parse-string(*) as a synonym and clarified in the docstring that the parse-sequence(*) functions takes anything implementing CONTEXT (which is list and vectors in parser-combinators itself).
