### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by arademaker** [Ramarren/cl-parser-combinators#4]
Hello Jakub,

Nice work! Thanks! Could you consider include in the doc directory one or two examples of parsers using the library? That would be nice to give us a better understanding of the library. One such example could be a parser for CSV files. I am planning to use this library to construct a paser for N3 files (http://www.w3.org/TeamSubmission/n3/).

BTW, I included in the Wikipedia page about parser combinator a link to this project.

Cheers,
Alexandre

**Comment by Ramarren** [comment]
I added a parser for CSV under doc/. Hopefully the comments are comprehensible.

**Comment by arademaker** [comment]
Wow! Thank you so much!! That will be very useful! I will study this example very carefully. Best, Alexandre

**Comment by Ramarren** [comment]
I made the example fairly quickly so please comment if you can see possible improvements. Or if the parser doesn't actually parse CSV, I tested it only on fairly limited examples.

**Comment by arademaker** [comment]
Yes. I will test and study the example. I will let you know in case of bugs or doubts!

**Comment by slyrus** [comment]
Didn't you have a lisp reader-like parser at some point? Or am I mis-remembering things? More examples would be very useful, as would more simple, but maybe tricky to get exactly right, constructs like floats, etc...

thanks!
