### ISSUE TITLE
between?, whitespace? and result type null

### ISSUE THREAD

**Issue by Neronus** [Ramarren/cl-parser-combinators#5]
`whitespace?` calls `between?` with `result-type` being `nil`

This leads to an error in `between?` because it tries to call `(coerce nil nil)`, which (at least on SBCL) results in an error.
Note that NIL is not really a type. Did you mean `NULL` (the type of `NIL`)?

Christian

**Comment by Ramarren** [comment]
Thank for the report. I didn't notice that `map` handles `nil` specially, but `coerce` does not. Changed to mapping over `nil`, which look a bit strange but at least is always consistent regarding the expected result type.

**Comment by Neronus** [comment]
Thank you for your quick reaction :)
